name: 'experimentation_metric_layer'
version: '1.0.0'
config-version: 2

profile: 'experimentation_metric_layer'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  experimentation_metric_layer:
    +materialized: view
    +database: experimentation
    metrics:
      +materialized: table
      +schema: metrics
    experiments:
      +materialized: table
      +schema: experiments
    anomaly_detection:
      +materialized: view
      +schema: quality
