experimentation_metric_layer:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      host: localhost
      port: 8080
      database: experimentation
      schema: public
      threads: 4
    prod:
      type: trino
      method: none
      host: "{{ env_var('TRINO_HOST') }}"
      port: 8080
      database: experimentation
      schema: public
      threads: 8
